Description: This template creates an Elasticache Redis cluster with MultiAZ support

Parameters:

  CacheNodeInstanceType:
    Description: Cache node instance type.
    Type: String
    Default: cache.t2.medium
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.m3.medium
      - cache.m3.large

  MultiAZSupport:
    Description: >-
      Indicates whether Multi-AZ is enabled. When Multi-AZ is enabled, a read-only
      replica is automatically promoted to a read-write primary cluster if the existing
      primary cluster fails. If you specify true, you must specify a value greater
      than 1 for the NumCacheClusters property.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  NumCacheClusters:
    Description: The number of cache clusters for this replication group. If MultiAZ
      support is enabled, you must specify a value greater than 1.
    Default: '2'
    Type: Number
    MinValue: '1'
    MaxValue: '3'

  RedisPort:
    Description: The port number on which each member of the replication group accepts
      connections.
    Type: Number
    Default: '6379'
    MinValue: '1'
    MaxValue: '65535'

  VpcId:
    Description: The VPC to create this ReplicationGroup under
    Type: AWS::EC2::VPC::Id

  PrivateSubnets:
    Description: List of the subnets you would like the ReplicationGroup to be created
      in.
    Type: List<AWS::EC2::Subnet::Id>

  SnapshotRetentionLimit:
    Description: The number of days that ElastiCache retains automatic snapshots before
      deleting them.
    Type: Number
    Default: '7'

  SnapshotWindow:
    Description: The time range (in UTC) when ElastiCache takes a daily snapshot of
      your node group.
    Type: String
    Default: '05:00-09:00'
    AllowedPattern: \d{2}:\d{2}-\d{2}:\d{2}
    ConstraintDescription: must be a valid timestamp range, for example 05:00-09:00

  PreferredMaintenanceWindow:
    Description: 'The weekly time range during which system maintenance can occur.
      Use the following format to specify a time range: ddd:hh24:mi-ddd:hh24:mi (24H
      Clock UTC).'
    Type: String
    Default: sun:22:00-sun:23:30
    AllowedPattern: (mon|tue|wed|thu|fri|sat|sun):\d{2}:\d{2}-(mon|tue|wed|thu|fri|sat|sun):\d{2}:\d{2}
    ConstraintDescription: must be a valid timestamp range with day of week, for example
      sun:22:00-sun:23:30

  pMasterStackName:
    Description: If nested, name of master stack
    Type: String


Resources:

  RedisAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref 'AWS::StackName'
      GroupDescription: Security Group for Elasticache Redis Replication Group
      VpcId: !Ref 'VpcId'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  RedisSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: RedisAccessSecurityGroup
    Properties:
      GroupId: !Ref 'RedisAccessSecurityGroup'
      IpProtocol: tcp
      FromPort: !Ref 'RedisPort'
      ToPort: !Ref 'RedisPort'
      SourceSecurityGroupId: !Ref 'RedisAccessSecurityGroup'

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet Group for Elasticache Redis Replication Group.
      SubnetIds:
        - !Select
          - 0
          - !Ref 'PrivateSubnets'
        - !Select
          - 1
          - !Ref 'PrivateSubnets'

  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AutomaticFailoverEnabled: !Ref 'MultiAZSupport'
      CacheNodeType: !Ref 'CacheNodeInstanceType'
      CacheSubnetGroupName: !Ref 'SubnetGroup'
      Engine: redis
      NumCacheClusters: !Ref 'NumCacheClusters'
      Port: !Ref 'RedisPort'
      PreferredMaintenanceWindow: !Ref 'PreferredMaintenanceWindow'
      ReplicationGroupDescription: Elasticache Redis cluster for Drupal
      SecurityGroupIds:
        - !GetAtt 'RedisAccessSecurityGroup.GroupId'
      SnapshotRetentionLimit: !Ref 'SnapshotRetentionLimit'
      SnapshotWindow: !Ref 'SnapshotWindow'


Outputs:

  RedisEndpoint:
    Description: The primary endpoint location
    Value: !Join
      - ''
      - - redis://
        - !GetAtt 'ReplicationGroup.PrimaryEndPoint.Address'
        - ':'
        - !GetAtt 'ReplicationGroup.PrimaryEndPoint.Port'
    Export:
      Name: !Join ['-', [ oRedisEndpoint, !Ref pMasterStackName ] ]

  RedisHost:
    Description: The primary redis host
    Value: !GetAtt 'ReplicationGroup.PrimaryEndPoint.Address'
    Export:
      Name: !Join ['-', [ oRedisHost, !Ref pMasterStackName ] ]

  RedisAccessSecurityGroup:
    Description: Redis access security group name
    Value: !Ref 'RedisAccessSecurityGroup'
    Export:
      Name: !Join ['-', [ oRedisAccessSecurityGroup, !Ref pMasterStackName ] ]
